version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - youbid-app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=db  # Reference to PostgreSQL service
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=youbid_db
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install && nodemon server.js"
    networks:
      - youbid-app

  db:
    image: postgres:13-alpine
    container_name: postgres_db_c
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youbid_db
    ports:
      - "5432:5432"
    networks:
      - youbid-app

volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  youbid-app:
    driver: bridge
