version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - youbid-app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install && nodemon server.js"
    networks:
      - youbid-app

volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  youbid-app:
    driver: bridge
